
name: dotnet ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Restore
      run: dotnet restore Quantra.sln
    - name: Build
      run: dotnet build Quantra.sln --configuration Release --no-restore
    - name: Test
      run: echo "Tests placeholder"
