
name: load-test

on:
  workflow_dispatch:

jobs:
  k6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Build
        run: dotnet build Quantra.sln --configuration Release
      - name: Start APIs
        run: |
          dotnet run --project src/Quantra.Transaction & 
          sleep 10
      - name: k6 load
        uses: grafana/k6-action@v0.3.1
        with:
          filename: ./tests/load_tx.js
